<?php

namespace Proxies\__CG__\eco\EcoleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eleve extends \eco\EcoleBundle\Entity\Eleve implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'datenaissance', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'genre', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'tel', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'nomtuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'adressetuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'teltuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'emailtuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'professiontuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'cintuteur');
        }

        return array('__isInitialized__', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'datenaissance', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'genre', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'tel', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'nomtuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'adressetuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'teltuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'emailtuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'professiontuteur', '' . "\0" . 'eco\\EcoleBundle\\Entity\\Eleve' . "\0" . 'cintuteur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eleve $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissance($datenaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissance', array($datenaissance));

        return parent::setDatenaissance($datenaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissance', array());

        return parent::getDatenaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', array($genre));

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', array());

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomtuteur($nomtuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomtuteur', array($nomtuteur));

        return parent::setNomtuteur($nomtuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomtuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomtuteur', array());

        return parent::getNomtuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressetuteur($adressetuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressetuteur', array($adressetuteur));

        return parent::setAdressetuteur($adressetuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressetuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressetuteur', array());

        return parent::getAdressetuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeltuteur($teltuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeltuteur', array($teltuteur));

        return parent::setTeltuteur($teltuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeltuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeltuteur', array());

        return parent::getTeltuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailtuteur($emailtuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailtuteur', array($emailtuteur));

        return parent::setEmailtuteur($emailtuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailtuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailtuteur', array());

        return parent::getEmailtuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfessiontuteur($professiontuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfessiontuteur', array($professiontuteur));

        return parent::setProfessiontuteur($professiontuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfessiontuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfessiontuteur', array());

        return parent::getProfessiontuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCintuteur($cintuteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCintuteur', array($cintuteur));

        return parent::setCintuteur($cintuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCintuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCintuteur', array());

        return parent::getCintuteur();
    }

}
